arguments:
  command: {type: str, help: Command to execute the application to watch}


exclusions:
  - re
  - string
  - difflib
  - textwrap
  - unicodedata
  - stringprep
  - readline
  - rlcompleter
  - struct
  - codecs
  - datetime
  - calendar
  - collections
  - collections.abc
  - heapq
  - bisect
  - array
  - weakref
  - types
  - copy
  - pprint
  - reprlib
  - enum
  - numbers
  - math
  - cmath
  - decimal
  - fractions
  - random
  - statistics
  - itertools
  - functools
  - operator 
  - pathlib
  - os.path
  - fileinput
  - stat
  - filecmp
  - tempfile
  - glob
  - fnmatch
  - linecache
  - shutil
  - macpath
  - pickle
  - copyreg
  - shelve
  - marshal
  - dbm
  - zlib
  - gzip 
  - bz2
  - lzma
  - zipfile
  - tarfile
  - csv
  - configparser
  - netrc
  - xdrlib
  - cProfile
  - profile
  - plistlib
  - hashlib
  - hmac
  - secrets
  - os
  - io
  - time
  - argparse
  - getopt
  - logging
  - logging.config
  - logging.handlers
  - getpass
  - curses
  - curses.textpad
  - curses.ascii
  - curses.panel
  - platform
  - errno
  - ctypes
  - threading
  - multiprocessing
  - concurrent.futures
  - subprocess
  - sched
  - queue
  - dummy_threading
  - _thread
  - _dummy_thread
  - socket
  - ssl
  - select
  - selectors
  - asyncio
  - asyncore
  - asynchat
  - signal
  - mmap
  - email
  - json
  - mailcap
  - mailbox
  - mimetypes
  - base64
  - binhex
  - binascii
  - quopri
  - uu
  - html
  - html.parser
  - html.entities
  - xml.etree.ElementTree
  - xml.dom
  - xml.dom.minidom
  - xml.dom.pulldom
  - xml.sax
  - xml.sax.handler
  - xml.sax.saxutils
  - xml.sax.xmlreader
  - xml.parsers.expat
  - webbrowser
  - cgi
  - cgitb
  - wsgiref
  - urllib
  - urllib.request
  - urllib.response
  - urllib.parse
  - urllib.error
  - urllib.robotparser
  - http
  - http.client
  - ftplib
  - poplib
  - imaplib
  - nntplib
  - smtplib
  - smtpd
  - telnetlib
  - uuid
  - socketserver
  - http.server
  - http.cookies
  - http.cookiejar
  - xmlrpc
  - xmlrpc.client
  - xmlrpc.server
  - ipaddress
  - audioop
  - aifc
  - sunau
  - wave
  - chunk
  - colorsys
  - imghdr
  - sndhdr
  - ossaudiodev
  - gettext
  - locale
  - turtle
  - cmd
  - shlex
  - tkinter
  - tkinter.ttk
  - tkinter.tix
  - tkinter.scrolledtext
  - typing
  - pydoc
  - doctest
  - unittest
  - unittest.mock
  - unittest.mock
  - 2to3
  - test
  - test.support
  - bdb
  - faulthandler
  - pdb
  - timeit
  - trace
  - tracemalloc
  - distutils
  - ensurepip
  - venv
  - zipapp
  - sys
  - sysconfig
  - builtins
  - __main__
  - warnings
  - contextlib
  - abc
  - atexit
  - traceback
  - __future__
  - gc
  - inspect
  - site
  - fpectl
  - code
  - codeop
  - zipimport
  - pkgutil
  - modulefinder
  - runpy
  - importlib
  - parser
  - ast
  - symtable
  - symbol
  - token
  - keyword
  - tokenize
  - tabnanny
  - pyclbr
  - py_compile
  - dis
  - pickletools
  - formatter
  - msilib
  - msvcrt
  - winreg
  - winsound
  - posix
  - pwd
  - spwd
  - grp
  - crypt
  - termios
  - tty
  - pty
  - fcntl
  - pipes
  - resource
  - nis
  - syslog
  - optparse
  - imp
  - future
  - six