language: python

python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly

cache: pip

install:
  - python setup.py install
  - pip install -r requirements.txt
  - pip install coverage
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - innuendo-agent --help

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT