language: python

python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly

cache: pip

install:
  - python setup.py install
  - pip install -r requirements.txt
  - pip install tox
  - if [[ $TRAVIS_PYTHON_VERSION == 3.2 ]]; then pip install coverage==3.7.1; else pip install coverage; fi
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

before_script:
  - ./cc-test-reporter before-build

script:
  - innuendo-agent --help
  - coverage run tests/runner.py -v
  - coverage xml -i
  - coverage report -m

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT